import type { Metadata } from "next";
import { Poppins, ABeeZee } from "next/font/google";
import 'antd/dist/reset.css';
import "./globals.css";
import { ConfigProvider } from "antd";
// import ReactLenis from "lenis/react";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});
const abzee = ABeeZee({
  variable: "--font-abzee-sans",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Infinity Developments",
  description: "Generated by create next app",
};

const theme = {
  token: {
    colorPrimary: "#0A0A0A",
    fontFamily: "'Poppins', 'sans-serif'",
    borderRadius: 6,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <ReactLenis root> */}
        <ConfigProvider theme={theme}>
          <body
            className={`${poppins.variable} ${abzee.variable} antialiased`}
          >
            {children}
          </body>
        </ConfigProvider>
      {/* </ReactLenis> */}
    </html>
  );
}
