import type { Metadata } from "next";
import { Poppins, ABeeZee} from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ['300', '400', '500','600','700', '800']
});
const abzee = ABeeZee({
  variable: "--font-abzee-sans",
  subsets: ["latin"],
  weight: ['400']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const theme = {
  token: {
    colorPrimary: "#0A0A0A", 
    fontFamily: "'Poppins', 'sans-serif'",
    borderRadius: 6,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <ConfigProvider theme={theme}>
       <body
        className={`${poppins.variable} ${abzee.variable}  antialiased`}
      >
        {children}
      </body>
     </ConfigProvider>
    </html>
  );
}
